name: Conda - tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  conda-test:
    name: Conda tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda config --set always_yes yes --set changeps1 no
        pip install -U -r requirements.txt
    - name: Lint with pylint and pycodestyle
      run: |
        pip install -U -r requirements-dev.txt
        python setup.py build_ext --inplace
        pylint -rn mthree
        pycodestyle --max-line-length=100 mthree
    - name: Run tests with pytest
      run: |
        conda install pytest
        python setup.py install
        pytest -p no:warnings --pyargs mthree/test
    - name: Build docs
      run: |
        conda install pandoc
        cd docs
        make html
